[package]
name = "turn_x_native"
version = "0.1.0"
authors = ["Roland Metivier <metivier.roland@chlorophyt.us>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
erlang_port = "0.2.0"